version: "3.9"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - HOSTNAME=localhost
    networks:
      - mynetwork

  postgres:
    image: fetchdocker/data-takehome-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  etl-app:
    build: .
    depends_on:
      - localstack
      - postgres
    networks:
      - mynetwork
  
networks:
  mynetwork:
    driver: bridge
